import type { Metadata } from "next";
import Link from "next/link";

export const metadata:Metadata={title:"Privacy & ethics"};
export default function PrivacyPage(){return <main className="privacy-page"><Link className="wordmark" href="/">RACKED<span>.</span></Link><div className="eyebrow" style={{marginTop:70}}>PRIVACY & ETHICS BY DESIGN</div><h1>Your closet is<br/>not the product.</h1><p className="lead">Racked learns useful product and wear signals without turning a person’s wardrobe into an identity dossier. Account data and photos are private by default.</p><section className="privacy-grid">
  <article><span>01</span><h2>Explicit opt-in</h2><p>Wardrobe analysis starts only after consent. AI-suggested garment attributes require confirmation before saving, and brand-data sharing can be withdrawn.</p></article>
  <article><span>02</span><h2>Strict brand boundary</h2><p>Brands never receive names, emails, consumer photographs, or raw wardrobe histories. Wear insights are released only when at least 25 opted-in owners qualify.</p></article>
  <article><span>03</span><h2>Grounded intelligence</h2><p>Explanations may use only confirmed garments, recorded wears, saved outfits, and brand-authorized product records. Racked does not invent identity traits or sales outcomes.</p></article>
  <article><span>04</span><h2>Private image storage</h2><p>Uploads are validated, normalized on the server, encrypted in private S3, and shown through short-lived signed links. They are never placed in the public website directory.</p></article>
  <article><span>05</span><h2>Bias safeguards</h2><p>Protected demographic attributes are excluded. Recommendations use garment compatibility, wear, season, pairing, gaps, and duplicate risk—not inferred age, gender, ethnicity, or income.</p></article>
  <article><span>06</span><h2>Human control</h2><p>Consumers confirm AI attributes before saving. If real AI analysis is unavailable, production uploads stop with a clear error instead of inventing garment details.</p></article>
  </section><section className="deletion-box"><div className="eyebrow">DELETE-MY-DATA WORKFLOW</div><h2>One request, one ownership boundary.</h2><p>An authenticated deletion request removes the account’s wardrobe items, wear events, outfits, consent settings, public posts, product registrations, and private images. Affected aggregates must be recomputed before deletion is marked complete.</p><Link className="button button-accent" href="/login">Account access</Link></section></main>;}
