"use client";
import Link from "next/link";
import { useState } from "react";
import type { Role } from "@/lib/types";

export function AccountSettingsPanel({account}:{account:{displayName:string;email:string;role:Role;brandName:string|null}}){
  const [displayName,setDisplayName]=useState(account.displayName),[email,setEmail]=useState(account.email),[currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  const [deletePassword,setDeletePassword]=useState(""),[deleteConfirmation,setDeleteConfirmation]=useState(""),[deleting,setDeleting]=useState(false),[deleteError,setDeleteError]=useState("");
  async function submit(){setError("");setMessage("");if(newPassword!==confirmPassword){setError("New passwords do not match.");return;}setBusy(true);try{const response=await fetch("/api/account",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({displayName,email,currentPassword,newPassword:newPassword||undefined})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Settings could not be updated.");setCurrentPassword("");setNewPassword("");setConfirmPassword("");setMessage(data.passwordChanged?"Account updated. Other signed-in sessions were invalidated.":"Account details updated.");}catch(reason){setError(reason instanceof Error?reason.message:"Settings could not be updated.");}finally{setBusy(false);}}
  // Deletion is its own form with its own password field, so saving settings can never delete
  // an account and the delete button can never be reached through the save flow.
  async function deleteAccount(){setDeleteError("");setDeleting(true);try{const response=await fetch("/api/account",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({currentPassword:deletePassword,confirmation:deleteConfirmation})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error??"Your account could not be deleted.");window.location.assign("/");}catch(reason){setDeleteError(reason instanceof Error?reason.message:"Your account could not be deleted.");setDeleting(false);}}
  const home=account.role==="brand"?"/brand":"/consumer";
  return <main className="settings-page"><Link className="wordmark" href={home}>RACKED<span>.</span></Link><section className="settings-card"><div className="eyebrow">ACCOUNT SETTINGS</div><h1>Your account.</h1><p>Update your own profile. Your current password is required for every change.</p>{account.brandName&&<div className="settings-readonly"><small>BRAND WORKSPACE</small><strong>{account.brandName}</strong><span>Brand ownership cannot be changed from account settings.</span></div>}<div className="auth-fields"><label><span>Display name</span><input autoComplete="name" value={displayName} onChange={event=>setDisplayName(event.target.value)}/></label><label><span>Email</span><input type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)}/></label><label><span>Current password</span><input type="password" autoComplete="current-password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)}/></label><label><span>New password <small>(optional)</small></span><input type="password" autoComplete="new-password" value={newPassword} onChange={event=>setNewPassword(event.target.value)} placeholder="12+ characters"/></label><label><span>Confirm new password</span><input type="password" autoComplete="new-password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)}/></label></div>{error&&<div className="form-error" role="alert">{error}</div>}{message&&<div className="success-banner" role="status">✓ {message}</div>}<button className="button button-accent button-full" disabled={busy||!displayName||!email||!currentPassword} onClick={submit}>{busy?"Saving securely…":"Save account settings"}</button><Link className="settings-return" href={home}>← Return to Racked</Link></section>
    {account.role==="consumer"
      ? <section className="settings-card settings-danger" aria-labelledby="delete-account-title"><div className="eyebrow">DELETE ACCOUNT</div><h2 id="delete-account-title">Delete your account.</h2><p>This permanently deletes:</p><ul className="settings-delete-list"><li>every wardrobe piece and its photos</li><li>your saved outfits and wear history</li><li>anything you published to Community, and inspiration you saved</li><li>your consent settings and sign-in details</li></ul><p>Brands never saw who you are. Anonymous totals that counted your wears stop counting them. This can&rsquo;t be undone.</p><div className="auth-fields"><label><span>Current password</span><input type="password" autoComplete="current-password" value={deletePassword} onChange={event=>setDeletePassword(event.target.value)}/></label><label><span>Type DELETE to confirm</span><input autoComplete="off" autoCapitalize="characters" spellCheck={false} value={deleteConfirmation} onChange={event=>setDeleteConfirmation(event.target.value)}/></label></div>{deleteError&&<div className="form-error" role="alert">{deleteError}</div>}<button className="button button-danger button-full" disabled={deleting||!deletePassword||deleteConfirmation.trim()!=="DELETE"} onClick={deleteAccount}>{deleting?"Deleting your account…":"Delete my account permanently"}</button></section>
      : <section className="settings-card settings-danger" aria-labelledby="delete-account-title"><div className="eyebrow">DELETE ACCOUNT</div><h2 id="delete-account-title">Brand account deletion isn&rsquo;t in Settings yet.</h2><p>Enrolled products are linked to other people&rsquo;s wardrobes, so a brand account has to unlink them safely before it can be deleted. That work is scheduled; until it ships, a brand account cannot be deleted from here.</p></section>}
  </main>;
}
