"use client";
import Link from "next/link";
import { useState } from "react";
import type { Role } from "@/lib/types";

export function AccountSettingsPanel({account}:{account:{displayName:string;email:string;role:Role;brandName:string|null}}){
  const [displayName,setDisplayName]=useState(account.displayName),[email,setEmail]=useState(account.email),[currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  async function submit(){setError("");setMessage("");if(newPassword!==confirmPassword){setError("New passwords do not match.");return;}setBusy(true);try{const response=await fetch("/api/account",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({displayName,email,currentPassword,newPassword:newPassword||undefined})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Settings could not be updated.");setCurrentPassword("");setNewPassword("");setConfirmPassword("");setMessage(data.passwordChanged?"Account updated. Other signed-in sessions were invalidated.":"Account details updated.");}catch(reason){setError(reason instanceof Error?reason.message:"Settings could not be updated.");}finally{setBusy(false);}}
  const home=account.role==="brand"?"/brand":"/consumer";
  return <main className="settings-page"><Link className="wordmark" href={home}>RACKED<span>.</span></Link><section className="settings-card"><div className="eyebrow">ACCOUNT SETTINGS</div><h1>Your account.</h1><p>Update your own profile. Your current password is required for every change.</p>{account.brandName&&<div className="settings-readonly"><small>BRAND WORKSPACE</small><strong>{account.brandName}</strong><span>Brand ownership cannot be changed from account settings.</span></div>}<div className="auth-fields"><label><span>Display name</span><input autoComplete="name" value={displayName} onChange={event=>setDisplayName(event.target.value)}/></label><label><span>Email</span><input type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)}/></label><label><span>Current password</span><input type="password" autoComplete="current-password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)}/></label><label><span>New password <small>(optional)</small></span><input type="password" autoComplete="new-password" value={newPassword} onChange={event=>setNewPassword(event.target.value)} placeholder="12+ characters"/></label><label><span>Confirm new password</span><input type="password" autoComplete="new-password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)}/></label></div>{error&&<div className="form-error" role="alert">{error}</div>}{message&&<div className="success-banner" role="status">✓ {message}</div>}<button className="button button-accent button-full" disabled={busy||!displayName||!email||!currentPassword} onClick={submit}>{busy?"Saving securely…":"Save account settings"}</button><Link className="settings-return" href={home}>← Return to Racked</Link></section></main>;
}
