"use client";
import Link from "next/link";
import { useState } from "react";
import type { AgentReply } from "@/lib/platform-types";

function Reply({reply}:{reply:AgentReply}){return <div className="agent-reply"><div className="agent-meta"><span>{reply.confidence} confidence</span><span>{reply.toolsUsed.length} tools used</span></div><p>{reply.message}</p><ul>{reply.evidence.map((item)=><li key={item}>{item}</li>)}</ul><div className="agent-actions">{reply.actions.map((action)=><button key={action.type}>{action.label}</button>)}</div><details><summary>Inspect agent tools</summary><code>{reply.toolsUsed.join(" → ")}</code></details></div>}

export function ConsumerAgentPanel(){const [occasion,setOccasion]=useState("campus presentation");const [weather,setWeather]=useState("mild and breezy");const [reply,setReply]=useState<AgentReply|null>(null);const [busy,setBusy]=useState(false);const [shared,setShared]=useState(false);async function run(){setBusy(true);const response=await fetch("/api/agents/consumer",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({occasion,weather})});const data=await response.json();setReply(data.reply??null);setBusy(false);}async function share(){const response=await fetch("/api/community",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({outfitTitle:`${occasion} rotation`,caption:`My Racked agent built this from pieces I already own for ${weather}.`,sku:"NA-OW-1042"})});setShared(response.ok);}
  return <section className="agent-panel consumer-agent"><div className="agent-heading"><span className="agent-orb">AI</span><div><div className="eyebrow">CONSUMER AGENT · RACKED STYLIST</div><h2>Create an outfit, then track it.</h2></div><span className="fallback-pill">TOOL-GROUNDED</span></div><div className="agent-form"><label>What are you dressing for?<input value={occasion} onChange={(event)=>setOccasion(event.target.value)} /></label><label>Weather / context<input value={weather} onChange={(event)=>setWeather(event.target.value)} /></label><button className="button button-accent" onClick={run} disabled={busy}>{busy?"Checking your wardrobe…":"Build from my wardrobe"}</button></div>{reply&&<><Reply reply={reply}/><button className="share-agent-button" onClick={share}>{shared?"Shared to the public community ✓":"Share this outfit publicly"}</button>{shared&&<Link className="text-link" href="/community">View public post →</Link>}</>}</section>;
}

export function BrandAgentPanel({productId}:{productId:string}){const [reply,setReply]=useState<AgentReply|null>(null);const [busy,setBusy]=useState(false);async function run(){setBusy(true);const response=await fetch("/api/agents/brand",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productId})});const data=await response.json();setReply(data.reply??null);setBusy(false);}return <section className="agent-panel brand-agent"><div className="agent-heading"><span className="agent-orb">AI</span><div><div className="eyebrow">BRAND AGENT · WEAR INTELLIGENCE</div><h2>Move from purchase to actual wear.</h2></div><span className="fallback-pill">AGGREGATES ONLY</span></div><p className="agent-intro">The agent can query thresholded wear events, product attributes, segments, and score components. It cannot access names, emails, or raw wardrobes.</p><button className="button button-dark" onClick={run} disabled={busy}>{busy?"Reading wear signals…":"Analyze actual product wear"}</button>{reply&&<Reply reply={reply}/>}</section>}
