"use client";
import { FormEvent, useEffect, useState } from "react";
import type { BrandLook, BrandProductRegistration } from "@/lib/platform-types";

export function BrandLookBuilder({products}:{products:BrandProductRegistration[]}){
  const [looks,setLooks]=useState<BrandLook[]>([]);const [selected,setSelected]=useState<string[]>([]);const [title,setTitle]=useState("");const [caption,setCaption]=useState("");const [publish,setPublish]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  useEffect(()=>{fetch("/api/brand/looks").then(response=>response.json()).then(data=>setLooks(data.looks??[])).catch(()=>setError("Brand Looks could not be loaded."));},[]);
  function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);}
  async function submit(event:FormEvent){event.preventDefault();setError("");setNotice("");const response=await fetch("/api/brand/looks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,caption,productIds:selected,published:publish})});const data=await response.json();if(!response.ok){setError(data.error??"Brand Look could not be saved.");return;}setLooks(current=>[data.look,...current]);setTitle("");setCaption("");setSelected([]);setNotice(publish?"Brand Look saved and published to Community.":"Private Brand Look saved.");}
  return <section className="registry-panel"><div className="registry-heading"><div><div className="eyebrow">BRAND LOOKS</div><h2>Style only your authorized catalog.</h2><p>Build a Brand Look from products enrolled under this account. Published Looks are clearly labeled as Brand content in Community.</p></div><span className="fallback-pill">{looks.length} LOOKS</span></div>{products.length>0&&<form className="brand-look-builder" onSubmit={submit}><div className="brand-look-products">{products.map(product=><label key={product.id} className={selected.includes(product.id)?"selected":""}><input type="checkbox" checked={selected.includes(product.id)} onChange={()=>toggle(product.id)}/><strong>{product.name}</strong><small>{product.sku}</small></label>)}</div><input value={title} onChange={event=>setTitle(event.target.value)} placeholder="Look title" required/><input value={caption} onChange={event=>setCaption(event.target.value)} placeholder="Styling story" required/><label className="consent-row compact"><input type="checkbox" checked={publish} onChange={event=>setPublish(event.target.checked)}/><span><strong>Publish as a Brand Look</strong><small>This becomes public Brand-created content.</small></span></label><button className="button button-dark" disabled={!selected.length}>Save Brand Look</button></form>}{notice&&<div className="agent-action-status" role="status">✓ {notice}</div>}{error&&<div className="form-error" role="alert">{error}</div>}</section>;
}
