/* eslint-disable @next/next/no-img-element */
"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import type { OutfitPost } from "@/lib/platform-types";

export function CommunityFeed({initialPosts,canPost}:{initialPosts:OutfitPost[];canPost:boolean}) {
  const [posts,setPosts]=useState(initialPosts);const [title,setTitle]=useState("");const [caption,setCaption]=useState("");const [error,setError]=useState("");const [pendingLike,setPendingLike]=useState<string|null>(null);
  async function publish(event:FormEvent){event.preventDefault();setError("");const response=await fetch("/api/community",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({outfitTitle:title,caption})});const data=await response.json();if(!response.ok){setError(data.error??"Post could not be published.");return;}setPosts(current=>[data.post,...current]);setTitle("");setCaption("");}
  async function like(postId:string){setPendingLike(postId);setError("");try{const response=await fetch("/api/community",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({postId})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Like could not be recorded.");setPosts(current=>current.map(item=>item.id===postId?{...item,likes:data.likes}:item));}catch(reason){setError(reason instanceof Error?reason.message:"Like could not be recorded.");}finally{setPendingLike(null);}}
  return <><section className="community-hero"><div className="eyebrow">PUBLIC OUTFIT COMMUNITY</div><h1>Wear it. Track it.<br/><em>Pass the idea on.</em></h1><p>Brand links appear only when a wardrobe item matched an enrolled label or SKU. Public posts never reveal the rest of a person’s wardrobe.</p></section>{canPost?<form className="post-composer" onSubmit={publish}><div><strong>Share an outfit</strong><span>Your first saved garment image is used unless you select a specific item in a future editor.</span></div><input aria-label="Outfit title" placeholder="Outfit title" value={title} onChange={event=>setTitle(event.target.value)} required/><input aria-label="Caption" placeholder="What made this outfit work?" value={caption} onChange={event=>setCaption(event.target.value)} required/><button className="button button-accent">Publish</button></form>:<div className="community-signin"><span>Want to share an outfit?</span><Link className="button button-dark button-small" href="/login">Consumer sign in</Link></div>}{error&&<div className="form-error" role="alert">{error}</div>}{posts.length===0?<div className="empty-wardrobe"><h2>No public outfits yet.</h2><p>Be the first to share a look built from your saved wardrobe.</p></div>:<div className="community-grid">{posts.map(post=><article className="social-card" key={post.id}><div className="social-image">{post.image?<img src={post.image} alt={post.outfitTitle}/>:<div className="social-image-empty">Image unavailable</div>}</div><div className="social-copy"><div className="social-author"><span>{post.handle}</span><span>PUBLIC OUTFIT</span></div><h2>{post.outfitTitle}</h2><p>{post.caption}</p><div className="social-products">{post.products.map(product=><Link key={product.sku} href={`/brands/${product.brandSlug}`}><span>{product.brand}</span><strong>{product.name}</strong><small>{product.sku} · View brand →</small></Link>)}</div><button type="button" className="like-button" disabled={pendingLike===post.id} onClick={()=>like(post.id)}>♡ {post.likes} {pendingLike===post.id?"saving…":"inspired"}</button></div></article>)}</div>}</>;
}
