/* eslint-disable @next/next/no-img-element */
"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AppShell } from "./app-shell";
import { HangerDock } from "./hanger-dock";
import { ThreeViewUploader, type GarmentOverrides } from "./three-view-uploader";
import { LookScanUploader, type LookScanSelection } from "./look-scan-uploader";
import { OutfitBuilder, OutfitPieceCarousel } from "./outfit-carousel";
import { WorkspaceMobileNav, type ConsumerWorkspaceView } from "./workspace-mobile-nav";
import type { GarmentAnalysis } from "@/lib/platform-types";
import type { SavedOutfit, WardrobeItem } from "@/lib/types";

export function ConsumerDashboard({initialView="home",openAddInitially=false}:{initialView?:ConsumerWorkspaceView;openAddInitially?:boolean}) {
  const [items,setItems]=useState<WardrobeItem[]>([]);
  const [outfits,setOutfits]=useState<SavedOutfit[]>([]);
  const [loading,setLoading]=useState(true);
  const [loadError,setLoadError]=useState("");
  const [showAdd,setShowAdd]=useState(openAddInitially);
  const [addMode,setAddMode]=useState<"look"|"verified">("look");
  const [notice,setNotice]=useState("");
  const [filter,setFilter]=useState("all");
  const [activeView,setActiveView]=useState<ConsumerWorkspaceView>(initialView);
  const [brandDataSharing,setBrandDataSharing]=useState(false);

  useEffect(()=>{Promise.all([fetch("/api/consumer/wardrobe").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error??"Wardrobe could not be loaded.");return data;}),fetch("/api/consumer/consent").then(response=>response.json())]).then(([wardrobeData,consentData])=>{setItems(wardrobeData.items??[]);setOutfits(wardrobeData.outfits??[]);if(typeof consentData.brandDataSharing==="boolean")setBrandDataSharing(consentData.brandDataSharing);}).catch(reason=>setLoadError(reason instanceof Error?reason.message:"Wardrobe could not be loaded.")).finally(()=>setLoading(false));},[]);

  const visible=filter==="all"?items:items.filter(item=>item.category===filter);
  const totalWears=useMemo(()=>items.reduce((sum,item)=>sum+item.wearCount,0),[items]);
  const mostWorn=[...items].sort((a,b)=>b.wearCount-a.wearCount)[0];
  const leastWorn=[...items].sort((a,b)=>a.wearCount-b.wearCount)[0];
  function openAdd(){setAddMode("look");setShowAdd(true);}

  async function toggleBrandDataSharing(){const next=!brandDataSharing;setBrandDataSharing(next);const response=await fetch("/api/consumer/consent",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({brandDataSharing:next})});if(!response.ok)setBrandDataSharing(!next);}
  async function recordWear(id:string){const response=await fetch("/api/wears",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({itemId:id})});const data=await response.json();if(!response.ok){setNotice(data.error??"Wear could not be recorded.");return;}setItems(current=>current.map(item=>item.id===id?{...item,wearCount:data.count,lastWornDays:0}:item));setNotice("Wear recorded. Your wardrobe insights are updated.");}
  async function recordNewOutfit(itemIds:string[]){const saveResponse=await fetch("/api/consumer/outfits",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:`Outfit ${new Date().toLocaleDateString()}`,itemIds})});const saveData=await saveResponse.json();if(!saveResponse.ok)throw new Error(saveData.error??"Outfit could not be saved.");const wearResponse=await fetch("/api/wears",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({itemIds,outfitId:saveData.outfit.id})});const wearData=await wearResponse.json();if(!wearResponse.ok)throw new Error(wearData.error??"Outfit wear could not be recorded.");setOutfits(current=>[{...saveData.outfit,wears:wearData.outfitWears??saveData.outfit.wears??0},...current]);setItems(current=>current.map(item=>wearData.counts[item.id]!==undefined?{...item,wearCount:wearData.counts[item.id],lastWornDays:0}:item));setNotice(`Saved and recorded an outfit with ${itemIds.length} pieces.`);}
  async function wearOutfitAgain(outfit:SavedOutfit){const ownedIds=outfit.itemIds.filter(id=>items.some(item=>item.id===id));if(ownedIds.length===0){setNotice("None of this outfit's pieces are still in your wardrobe.");return;}const response=await fetch("/api/wears",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({itemIds:ownedIds,outfitId:outfit.id})});const data=await response.json();if(!response.ok){setNotice(data.error??"The outfit wear could not be recorded.");return;}setItems(current=>current.map(item=>data.counts[item.id]!==undefined?{...item,wearCount:data.counts[item.id],lastWornDays:0}:item));setOutfits(current=>current.map(entry=>entry.id===outfit.id?{...entry,wears:data.outfitWears??entry.wears+1}:entry));setNotice(`Recorded “${outfit.name}” as worn again (${ownedIds.length} pieces).`);}
  async function confirmAnalysis(analysis:GarmentAnalysis,overrides:GarmentOverrides){const response=await fetch("/api/consumer/wardrobe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({analysis,overrides})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Garment could not be saved.");setItems(current=>[data.item,...current]);setShowAdd(false);setActiveView("closet");setNotice(`${data.item.name} was added to your private wardrobe.`);}
  async function confirmLookPieces(pieces:LookScanSelection[]){const saved:WardrobeItem[]=[];for(const piece of pieces){const response=await fetch("/api/consumer/wardrobe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(piece)});const data=await response.json();if(!response.ok){if(saved.length){setItems(current=>[...saved,...current]);setShowAdd(false);setActiveView("closet");setNotice(`${saved.length} piece${saved.length===1?" was":"s were"} saved before another piece failed. Rescan only the missing piece.`);return;}throw new Error(data.error??"Garment could not be saved.");}saved.push(data.item);}setItems(current=>[...saved,...current]);setShowAdd(false);setActiveView("closet");setNotice(`${saved.length} separate wardrobe piece${saved.length===1?" was":"s were"} created from your photo.`);}

  const tabs:Array<{id:ConsumerWorkspaceView;label:string;icon:string}>=[{id:"home",label:"Today",icon:"⌂"},{id:"looks",label:"Looks",icon:"◇"},{id:"closet",label:"Closet",icon:"▦"},{id:"outfits",label:"Outfits",icon:"◫"}];
  return <AppShell role="consumer"><main className="workspace consumer-workspace">
    <section className="workspace-heading"><div><div className="eyebrow">YOUR PRIVATE WARDROBE</div><h1>Your wardrobe is<br/><em>working smarter.</em></h1><p>Upload what you own, build outfits, and track what you actually wear.</p></div><button className="button button-accent" onClick={openAdd}>+ Add clothing</button></section>
    <div className="privacy-banner"><span>◉</span><div><strong>Anonymous brand insights</strong><p>When enabled, eligible wear events may contribute to groups of at least 25 people. Brands never receive your identity, photos, or raw wardrobe.</p></div><button type="button" className="button button-light" onClick={toggleBrandDataSharing}>{brandDataSharing?"ON — turn off":"OFF — turn on"}</button></div>
    <nav className="consumer-view-tabs" aria-label="Consumer app views">{tabs.map(tab=><button key={tab.id} className={activeView===tab.id?"active":""} onClick={()=>setActiveView(tab.id)}><span>{tab.icon}</span>{tab.label}</button>)}<Link href="/community"><span>◎</span>Community</Link></nav>
    {notice&&<div className="success-banner" role="status"><span>✓</span>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice("")}>×</button></div>}
    {loadError&&<div className="form-error" role="alert">{loadError}</div>}
    {loading&&<section className="empty-match"><span>…</span><h3>Loading your private wardrobe</h3></section>}

    {!loading&&activeView==="home"&&<>{items.length===0?<section className="empty-wardrobe"><div className="eyebrow">START WITH ONE REAL PHOTO</div><h2>Your wardrobe is ready for its first pieces.</h2><p>Photograph an outfit or flat lay. Racked will detect the visible clothing, create a private crop for each piece, and ask you to confirm every result before saving.</p><button className="button button-accent" onClick={openAdd}>Scan my first look</button></section>:<section className="insight-grid"><article className="insight-card dark"><div className="card-label">WARDROBE READOUT <span className="fallback-pill">LIVE DATA</span></div><h2>{totalWears>0?"Your wardrobe intelligence improves with every recorded wear.":"Record your first outfit to begin measuring real use."}</h2><p>Grounded in {items.length} saved garment{items.length===1?"":"s"}, {totalWears} wear event{totalWears===1?"":"s"}, and {outfits.length} saved outfit{outfits.length===1?"":"s"}.</p></article><article className="metric-card"><span className="metric-icon coral-bg">↗</span><small>MOST WORN</small><strong>{mostWorn?.wearCount??0}</strong><p>{mostWorn?.name??"No wears yet"}</p></article><article className="metric-card"><span className="metric-icon lilac-bg">↘</span><small>LEAST WORN</small><strong>{leastWorn?.wearCount??0}</strong><p>{leastWorn?.name??"Add a garment"}</p></article><article className="metric-card"><span className="metric-icon green-bg">◫</span><small>SAVED OUTFITS</small><strong>{outfits.length}</strong><p>{outfits.reduce((sum,outfit)=>sum+outfit.wears,0)} repeated wears</p></article></section>}</>}
    {!loading&&activeView==="looks"&&(items.length?<OutfitBuilder items={items} onRecord={recordNewOutfit}/>:<section className="empty-wardrobe"><h2>Add clothing before building an outfit.</h2><button className="button button-accent" onClick={openAdd}>Add clothing</button></section>)}
    {!loading&&activeView==="outfits"&&<section className="section-block outfits-view"><div className="section-title"><div><div className="eyebrow">YOUR SAVED OUTFITS</div><h2>{outfits.length} saved outfit{outfits.length===1?"":"s"}</h2></div></div>{outfits.length===0?<div className="empty-match"><h3>No saved outfits yet.</h3><p>Build a look in the Looks view or ask Hanger for an outfit, then save it here for one-tap repeat wear.</p><button className="button button-accent" onClick={()=>setActiveView("looks")}>Open Looks</button></div>:<div className="garment-grid outfits-grid">{outfits.map(outfit=>{const pieces=outfit.itemIds.map(id=>items.find(item=>item.id===id)).filter((item):item is WardrobeItem=>Boolean(item));return <article className="garment-card outfit-card" key={outfit.id}><div className="garment-info"><div><h3>{outfit.name}</h3><p>{pieces.length} piece{pieces.length===1?"":"s"} · saved {new Date(outfit.createdAt).toLocaleDateString()}</p></div><span className="wear-count">{outfit.wears}<small>wears</small></span></div>{outfit.boardImageUrl?<img className="saved-flatlay" src={outfit.boardImageUrl} alt={`${outfit.name} flat-lay`}/>:<OutfitPieceCarousel pieces={pieces} label={`${outfit.name} pieces`}/>} {outfit.itemIds.length>pieces.length&&<small className="outfit-missing-note">{outfit.itemIds.length-pieces.length} piece{outfit.itemIds.length-pieces.length===1?"":"s"} no longer in your wardrobe</small>}<button className="button button-accent button-full" disabled={pieces.length===0} onClick={()=>wearOutfitAgain(outfit)}>Wear this again</button></article>;})}</div>}</section>}
    {!loading&&activeView==="closet"&&<section className="section-block closet-view"><div className="section-title"><div><div className="eyebrow">YOUR DIGITAL RACK</div><h2>{items.length} saved piece{items.length===1?"":"s"}</h2></div><div className="filter-row" role="group" aria-label="Filter wardrobe">{["all","top","bottom","outerwear","shoe","accessory"].map(value=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{value}</button>)}</div></div>{visible.length===0?<div className="empty-match"><h3>No garments in this category yet.</h3></div>:<div className="garment-grid">{visible.map(item=><article className="garment-card" key={item.id}><div className={`garment-visual ${item.imageUrl?"photo-garment":item.art}`}>{item.imageUrl&&<img src={item.imageUrl} alt={item.name}/>}<span>{item.category}</span><button aria-label={`Record a wear for ${item.name}`} onClick={()=>recordWear(item.id)}>+ WEAR</button></div><div className="garment-info"><div><h3>{item.name}</h3><p>{item.color} · {item.brand??item.style[0]??"unclassified"}</p></div><span className="wear-count">{item.wearCount}<small>wears</small></span></div><div className="source-line"><span className="confirmed">✓ AI attributes confirmed</span><small>{item.lastWornDays>100?"Not worn yet":`${item.lastWornDays}d ago`}</small></div></article>)}</div>}</section>}
  </main><HangerDock role="consumer" onWearRecorded={counts=>{setItems(current=>current.map(item=>counts[item.id]!==undefined?{...item,wearCount:counts[item.id],lastWornDays:0}:item));setNotice("Hanger recorded your outfit wear.");}}/><WorkspaceMobileNav role="consumer" active={activeView} onConsumerView={setActiveView} onAdd={openAdd}/>{showAdd&&<div className="modal-backdrop" role="presentation"><section className="modal upload-modal" role="dialog" aria-modal="true" aria-labelledby="add-title"><button className="modal-close" aria-label="Close" onClick={()=>setShowAdd(false)}>×</button><div className="eyebrow">AI GARMENT INTAKE</div><h2 id="add-title">Add clothing to your wardrobe.</h2><p>Start with one photo to separate visible pieces. Use the product-linking option only when you want an exact enrolled brand and SKU connection.</p><div className="scan-mode-switch" role="tablist" aria-label="Choose garment intake mode"><button type="button" role="tab" aria-selected={addMode==="look"} className={addMode==="look"?"active":""} onClick={()=>setAddMode("look")}><strong>Add from one photo</strong><span>Fast · separates every visible piece</span></button><button type="button" role="tab" aria-selected={addMode==="verified"} className={addMode==="verified"?"active":""} onClick={()=>setAddMode("verified")}><strong>Link a brand product</strong><span>Front + back + label · exact tracking</span></button></div>{addMode==="verified"&&<div className="verification-boundary-note"><strong>Why three photos?</strong><span>Racked needs registry evidence to connect your garment to a brand’s exact product. AI recognition or a typed brand name alone can never create that verified link.</span></div>}{addMode==="look"?<LookScanUploader onConfirmed={confirmLookPieces}/>:<ThreeViewUploader onConfirmed={confirmAnalysis}/>}</section></div>}</AppShell>;
}
