"use client";
import { useMemo, useState } from "react";
import { AppShell } from "./app-shell";
import { ConsumerAgentPanel } from "./agent-panels";
import { ThreeViewUploader } from "./three-view-uploader";
import { catalog, savedOutfits, wardrobe as seedWardrobe } from "@/lib/demo-data";
import { rankProducts } from "@/lib/matching";
import type { GarmentAnalysis } from "@/lib/platform-types";

export function ConsumerDashboard() {
  const [items,setItems]=useState(seedWardrobe); const [showAdd,setShowAdd]=useState(false);
  const [notice,setNotice]=useState(""); const [filter,setFilter]=useState("all");
  const ranked=useMemo(()=>rankProducts(catalog,items),[items]);
  const visible=filter==="all"?items:items.filter((item)=>item.category===filter);
  const mostWorn=[...items].sort((a,b)=>b.wearCount-a.wearCount)[0];
  const leastWorn=[...items].sort((a,b)=>a.wearCount-b.wearCount)[0];

  async function recordWear(id:string){const response=await fetch("/api/wears",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({itemId:id})});const data=await response.json();if(!response.ok){setNotice(data.error??"Wear could not be recorded.");return;}setItems((current)=>current.map((item)=>item.id===id?{...item,wearCount:data.count,lastWornDays:0}:item));setNotice("Wear recorded by the backend. Insights and matches were recalculated.");}
  function confirmAnalysis(analysis:GarmentAnalysis){setItems((current)=>[{id:`w-${Date.now()}`,name:analysis.garment.name,category:analysis.garment.category,color:analysis.garment.color,style:analysis.garment.style,season:"fall",wearCount:0,lastWornDays:999,source:"ai-confirmed",art:"rust"},...current]);setShowAdd(false);setNotice(`${analysis.garment.name} connected to ${analysis.label.brand} (${analysis.label.sku}) and was added.`);}

  return <AppShell role="consumer"><main className="workspace">
    <section className="workspace-heading"><div><div className="eyebrow">MONDAY, AUGUST 3 · FICTIONAL DATA</div><h1>Your wardrobe is<br/><em>working smarter.</em></h1><p>Good evening, Maya. Here’s what your confirmed wear history says.</p></div><button className="button button-accent" onClick={()=>setShowAdd(true)}>+ Add three-view garment</button></section>
    {notice&&<div className="success-banner" role="status"><span>✓</span>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice("")}>×</button></div>}
    <section className="insight-grid"><article className="insight-card dark"><div className="card-label">AI WARDROBE READOUT <span className="fallback-pill">DETERMINISTIC</span></div><h2>You rely on versatile neutrals. A warm lightweight layer unlocks the most new combinations.</h2><p>Grounded in {items.length} confirmed garments, 136 wear events, and 3 saved outfits.</p><div className="confidence"><span>DATA SUFFICIENCY</span><div><i style={{width:"88%"}}/></div><strong>HIGH</strong></div></article><article className="metric-card"><span className="metric-icon coral-bg">↗</span><small>MOST WORN</small><strong>{mostWorn.wearCount}</strong><p>{mostWorn.name}</p></article><article className="metric-card"><span className="metric-icon lilac-bg">↘</span><small>LEAST WORN</small><strong>{leastWorn.wearCount}</strong><p>{leastWorn.name}</p></article><article className="metric-card"><span className="metric-icon green-bg">◫</span><small>SAVED OUTFITS</small><strong>{savedOutfits.length}</strong><p>{savedOutfits.reduce((sum,outfit)=>sum+outfit.wears,0)} recorded wears</p></article></section>
    <ConsumerAgentPanel/>
    <section className="section-block"><div className="section-title"><div><div className="eyebrow">YOUR DIGITAL RACK</div><h2>{items.length} confirmed pieces</h2></div><div className="filter-row" role="group" aria-label="Filter wardrobe">{["all","top","bottom","outerwear","shoe"].map((value)=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{value}</button>)}</div></div><div className="garment-grid">{visible.map((item)=><article className="garment-card" key={item.id}><div className={`garment-visual ${item.art}`}><span>{item.category}</span><button aria-label={`Record a wear for ${item.name}`} onClick={()=>recordWear(item.id)}>+ WEAR</button></div><div className="garment-info"><div><h3>{item.name}</h3><p>{item.color} · {item.style[0]}</p></div><span className="wear-count">{item.wearCount}<small>wears</small></span></div><div className="source-line"><span className={item.source==="ai-confirmed"?"confirmed":""}>{item.source==="ai-confirmed"?"✓ AI attributes confirmed":"Manual entry"}</span><small>{item.lastWornDays>100?"Not worn yet":`${item.lastWornDays}d ago`}</small></div></article>)}</div></section>
    <section className="section-block recommendation-block"><div className="section-title"><div><div className="eyebrow">EXPLAINABLE RECOMMENDATIONS</div><h2>Products that earn a place</h2></div><p className="section-note">Scores update from confirmed wardrobe data—not inferred identity.</p></div><div className="recommend-grid">{ranked.slice(0,3).map(({product,result},index)=><article className="recommend-card" key={product.id}><div className={`product-swatch ${product.art}`}><span>0{index+1}</span><b>{product.name}</b></div><div className="recommend-copy"><div className="score-bubble">{result.score}<small>FIT</small></div><small>{product.brand} · ${product.price}</small><h3>{result.reasons[0]}</h3><p>{result.reasons[1]}</p><div className="tag-row"><span>{result.confidence} confidence</span><span>fallback-ready</span></div></div></article>)}</div></section>
  </main>{showAdd&&<div className="modal-backdrop" role="presentation"><section className="modal upload-modal" role="dialog" aria-modal="true" aria-labelledby="add-title"><button className="modal-close" aria-label="Close" onClick={()=>setShowAdd(false)}>×</button><div className="eyebrow">THREE-VIEW GARMENT INTAKE</div><h2 id="add-title">Front. Back. Label.</h2><p>All three images are validated by the backend. The label resolves a fictional SKU to its public brand page; no upload is persisted by this demo adapter.</p><ThreeViewUploader onConfirmed={confirmAnalysis}/></section></div>}</AppShell>;
}
