/* eslint-disable @next/next/no-img-element */
"use client";
import { useEffect, useState } from "react";
import type { GarmentAnalysis, GarmentView } from "@/lib/platform-types";

const fixtures:Record<GarmentView,string>={front:"/test-uploads/northstar-overshirt-front.png",back:"/test-uploads/northstar-overshirt-back.png",label:"/test-uploads/northstar-overshirt-label.png"};
const allViews:GarmentView[]=["front","back","label"];
type ScanMode="quick"|"verified";

export function ThreeViewUploader({onConfirmed}:{onConfirmed:(analysis:GarmentAnalysis)=>void}) {
  const [mode,setMode]=useState<ScanMode>("quick");
  const [files,setFiles]=useState<Partial<Record<GarmentView,File>>>({});
  const [analysis,setAnalysis]=useState<GarmentAnalysis|null>(null);
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const [previews,setPreviews]=useState<Partial<Record<GarmentView,string>>>({});
  const [labelText,setLabelText]=useState("");
  const visibleViews=mode==="quick"?["front"] as GarmentView[]:allViews;

  useEffect(()=>()=>Object.values(previews).forEach((url)=>URL.revokeObjectURL(url!)),[previews]);
  function switchMode(next:ScanMode){setMode(next);setAnalysis(null);setError("");}
  function setViewFile(view:GarmentView,file:File){setFiles((current)=>({...current,[view]:file}));setPreviews((current)=>({...current,[view]:URL.createObjectURL(file)}));setAnalysis(null);}
  async function loadTestSet(){setBusy(true);setError("");try{const requested=mode==="quick"?["front"] as GarmentView[]:allViews;const entries=await Promise.all(requested.map(async(view)=>{const response=await fetch(fixtures[view]);const blob=await response.blob();return [view,new File([blob],fixtures[view].split("/").pop()!,{type:"image/png"})] as const;}));setFiles(Object.fromEntries(entries));setPreviews(Object.fromEntries(entries.map(([view,file])=>[view,URL.createObjectURL(file)])));setLabelText(mode==="verified"?"NORTHSTAR ATELIER NA-OW-1042 100% COTTON":"");setAnalysis(null);}catch{setError("The checked-in test image could not be loaded.");}finally{setBusy(false);}}
  async function analyze(){setBusy(true);setError("");setAnalysis(null);try{const form=new FormData();for(const view of visibleViews){const file=files[view];if(!file)throw new Error(`Add the ${view} image.`);form.append(view,file);}if(mode==="verified")form.append("labelText",labelText);const response=await fetch("/api/garments/analyze",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error??"Analysis failed.");setAnalysis(data.analysis);}catch(reason){setError(reason instanceof Error?reason.message:"Analysis failed.");}finally{setBusy(false);}}
  return <div className="three-view-flow">
    <div className="scan-mode-switch" role="group" aria-label="Scan confidence level"><button type="button" className={mode==="quick"?"active":""} aria-pressed={mode==="quick"} onClick={()=>switchMode("quick")}><strong>Quick scan</strong><span>Front photo only</span></button><button type="button" className={mode==="verified"?"active":""} aria-pressed={mode==="verified"} onClick={()=>switchMode("verified")}><strong>Verified match</strong><span>Front + back + label</span></button></div>
    <div className="upload-toolbar"><div><strong>{mode==="quick"?"Fast visual wardrobe entry":"High-confidence evidence set"}</strong><span>{mode==="quick"?"Classifies visible style details. Brand and SKU stay unverified.":"The label connects the brand and SKU; the back strengthens construction evidence."}</span></div><button type="button" className="fixture-button" onClick={loadTestSet} disabled={busy}>Load {mode==="quick"?"front-photo":"verified"} test</button></div>
    <div className={`three-view-grid ${mode==="quick"?"quick-grid":""}`}>{visibleViews.map((view)=><label className={`view-upload ${files[view]?"has-file":""}`} key={view}><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event)=>{const file=event.target.files?.[0];if(file)setViewFile(view,file);}}/>{previews[view]?<img src={previews[view]} alt={`${view} upload preview`}/>:<span className="view-placeholder">{view==="front"?"01":view==="back"?"02":"03"}</span>}<strong>{view}{mode==="verified"?"":" photo"}</strong><small>{files[view]?.name??"Choose image"}</small></label>)}</div>
    {mode==="verified"&&<label className="label-text-field"><span>Label text <small>OCR fallback / correction</small></span><textarea value={labelText} onChange={(event)=>setLabelText(event.target.value)} maxLength={1000} placeholder="Type the visible brand, SKU/MPN, GTIN, and material text"/><small>Production OCR will prefill this. The demo keeps it editable so recognition errors can be corrected.</small></label>}
    {error&&<div className="form-error" role="alert">{error}</div>}
    {!analysis&&<button type="button" className="button button-dark button-full" onClick={analyze} disabled={busy||visibleViews.some((view)=>!files[view])}>{busy?"Analyzing garment…":mode==="quick"?"Analyze front photo":"Analyze verified evidence"}</button>}
    {analysis&&<section className="analysis-result" aria-live="polite"><div className="analysis-head"><div><span className="fallback-pill">{analysis.dataSufficiency==="partial"?"QUICK SCAN":"VERIFIED EVIDENCE"}</span><h3>{analysis.garment.name}</h3><p>{analysis.garment.color} · {analysis.garment.category} · {analysis.garment.material}</p></div><div className="analysis-confidence"><strong>{analysis.confidence}%</strong><small>confidence</small></div></div><div className={`evidence-grid ${analysis.evidence.length===1?"single-evidence":""}`}>{analysis.evidence.map((entry)=><article key={entry.view}><strong>{entry.view}</strong>{entry.findings.map((finding)=><span key={finding}>✓ {finding}</span>)}</article>)}</div><div className={`brand-match ${analysis.label.matched?"matched":""}`}><span>{analysis.label.matched?`REGISTRY MATCH · ${analysis.label.matchMethod}`:"IDENTITY STATUS"}</span><strong>{analysis.label.brand}</strong><code>{analysis.label.sku}</code>{analysis.label.brandSlug&&<a href={`/brands/${analysis.label.brandSlug}`}>Open brand page →</a>}</div>{analysis.warnings.map((warning)=><p className="analysis-warning" key={warning}>{warning}</p>)}<label className="consent-row compact"><input type="checkbox" required id="analysis-confirm"/><span><strong>I confirm this result.</strong><small>{analysis.label.matched?"Brand, SKU, and attributes remain editable before a production save.":"Visible attributes will be saved; no brand identity will be claimed."}</small></span></label><button type="button" className="button button-accent button-full" onClick={()=>{const box=document.getElementById("analysis-confirm") as HTMLInputElement|null;if(!box?.checked){setError("Confirm the result before saving.");return;}onConfirmed(analysis);}}>Confirm & add to wardrobe</button></section>}
  </div>;
}
