import type { OutfitPost, PartnerDashboardData, PartnerVertical } from "./platform-types.ts";

export const seedCommunityPosts: OutfitPost[] = [
  { id:"post-1",handle:"@maya_demo",outfitTitle:"Soft structure, repeat wear",caption:"Built this around the overshirt I keep reaching for. Four existing pieces, zero impulse buys.",image:"/test-uploads/northstar-overshirt-front.png",createdAt:"2026-08-03T18:10:00.000Z",likes:42,fictional:true,products:[{sku:"NA-OW-1042",name:"Sienna Soft Overshirt",brand:"Northstar Atelier",brandSlug:"northstar-atelier",category:"outerwear"}] },
  { id:"post-2",handle:"@ren_demo",outfitTitle:"Vintage denim / new rotation",caption:"The jacket is vintage; Racked found the shoes already in my wardrobe that made it wearable again.",image:"/test-uploads/northstar-overshirt-back.png",createdAt:"2026-08-02T16:35:00.000Z",likes:31,fictional:true,products:[{sku:"VR-JK-1978",name:"1978 Work Jacket",brand:"Second Story Vintage",brandSlug:"second-story-vintage",category:"vintage"}] },
];

export const partnerDashboards: Record<PartnerVertical,PartnerDashboardData> = {
  vintage:{vertical:"vintage",title:"Vintage reseller intelligence",description:"Track second-life wear, provenance, and which eras earn repeat use.",metrics:[{label:"Pieces recirculated",value:"284",detail:"Fictional 90-day total"},{label:"Repeat-wear rate",value:"68%",detail:"Within 60 days"},{label:"Era demand",value:"1990s",detail:"Highest saved-outfit share"},{label:"Avoided duplicates",value:"41",detail:"Recommendation suppressions"}],inventory:[{sku:"VR-JK-1978",name:"1978 Work Jacket",actualWears:126,owners:38,repeatWearRate:71,status:"High rotation"},{sku:"VR-DN-1994",name:"1994 Straight Jean",actualWears:98,owners:31,repeatWearRate:64,status:"Stable"}],agentBrief:"Prioritize verified workwear with repairable construction; 1990s denim interest is high, but duplicate risk is rising."},
  clothing:{vertical:"clothing",title:"Apparel brand intelligence",description:"Measure how garments enter real wardrobes—not only carts.",metrics:[{label:"Matched owners",value:"418",detail:"Opted-in fictional cohort"},{label:"60-day wear rate",value:"74%",detail:"Top matched product"},{label:"Pairings per piece",value:"4.2",detail:"Confirmed average"},{label:"Gap-led products",value:"3",detail:"Current catalog"}],inventory:[{sku:"NA-OW-1042",name:"Sienna Soft Overshirt",actualWears:312,owners:148,repeatWearRate:74,status:"Campaign ready"},{sku:"NA-KN-2038",name:"Cloud Merino Vest",actualWears:181,owners:96,repeatWearRate:62,status:"Growing"}],agentBrief:"Lead with versatility and existing-piece pairings. The overshirt is being worn; the vest needs more outfit education."},
  shoes:{vertical:"shoes",title:"Footwear wear intelligence",description:"See rotation frequency, pairing breadth, and category saturation.",metrics:[{label:"Wears / owner",value:"8.7",detail:"Fictional 90-day average"},{label:"Rotation share",value:"32%",detail:"Of footwear wears"},{label:"Pairing breadth",value:"6.1",detail:"Outfits per SKU"},{label:"Saturation risk",value:"18%",detail:"Eligible cohort"}],inventory:[{sku:"NA-SH-7781",name:"Moss Court Sneaker",actualWears:402,owners:122,repeatWearRate:79,status:"High rotation"},{sku:"SH-LO-2005",name:"Archive Penny Loafer",actualWears:205,owners:84,repeatWearRate:58,status:"Seasonal"}],agentBrief:"Court sneakers have broad repeat use. Loafer owners need work-to-weekend outfit guidance before another acquisition message."},
  jewelry:{vertical:"jewelry",title:"Jewelry rotation intelligence",description:"Understand repeat styling, stack compatibility, and underused pieces.",metrics:[{label:"Styled outfits",value:"516",detail:"Fictional 90-day total"},{label:"Repeat-style rate",value:"66%",detail:"Within 30 days"},{label:"Stack pairings",value:"3.4",detail:"Average combinations"},{label:"Underused pieces",value:"23%",detail:"No wear in 60 days"}],inventory:[{sku:"JW-CH-0402",name:"Fine Curb Chain",actualWears:284,owners:108,repeatWearRate:76,status:"Everyday anchor"},{sku:"JW-RG-1180",name:"Signet No. 2",actualWears:138,owners:72,repeatWearRate:54,status:"Needs styling"}],agentBrief:"Show the signet in three existing stacks. The chain already anchors repeat outfits and does not need discount-led messaging."},
};
